global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "inference_server"
    static_configs:
      - targets: ["localhost:5000"]

  - job_name: "inference_exporter"
    static_configs:
      - targets: ["localhost:8000"]