name: ncf-env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.2=pyhc872135_1
  - psutil=7.0.0=py312hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - alembic==1.17.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.73.0
      - docker==7.1.0
      - fastapi==0.121.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.15.1
      - huey==2.5.4
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mlflow==2.19.0
      - mlflow-skinny==2.19.0
      - mlflow-tracing==3.6.0
      - namex==0.1.0
      - numpy==2.3.4
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - protobuf==5.29.5
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - scikeras==0.13.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.49.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /home/leo/miniconda3/envs/ncf-env
